<template>
  <div class="index-page">
    <h1>Nuxt Playground</h1>
    <button @click="showPopup">OpenPopup</button>

    <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis libero turpis. Etiam vitae congue lorem, vel suscipit magna. Aenean sed eleifend metus. In mattis, justo sit amet sollicitudin placerat, ligula mauris aliquam lectus, quis rhoncus ex ipsum eu mi. Sed fringilla semper metus, eget pharetra urna vulputate vitae. Etiam scelerisque est ut feugiat tempor. Cras at diam lacinia, sodales libero a, porta quam. Proin luctus tincidunt efficitur. Maecenas ligula enim, lobortis vel mauris nec, efficitur egestas nibh.

      Integer a libero a ligula vulputate porta sit amet vitae nunc. Fusce malesuada orci lectus, a luctus dolor elementum eu. Suspendisse bibendum interdum ligula sit amet egestas. Nunc ac posuere ante. Nullam porttitor ex ut interdum efficitur. Ut posuere bibendum metus a aliquet. Curabitur quis imperdiet purus. Praesent ut justo non augue tempus facilisis at eu erat. Nulla eu tempor sem, id mattis dolor. Cras ultrices cursus tellus ut interdum.

      Nam vitae arcu a nisl faucibus accumsan. Morbi sed fringilla sapien, at euismod ex. Quisque iaculis eleifend massa interdum cursus. Donec gravida dolor quis nunc lacinia, ac euismod sapien fermentum. Sed eleifend convallis justo et vehicula. Praesent tristique turpis sed molestie tristique. Curabitur non arcu quis libero hendrerit vestibulum in ut nibh. Ut nec elementum turpis, sit amet suscipit sem. Nam venenatis ligula dui, at consectetur est molestie eu. Nullam sed leo sit amet tortor tincidunt sagittis non a nulla. Sed a tristique augue. Quisque in porttitor lacus. Maecenas egestas vulputate ante quis semper. Vestibulum congue aliquet augue non consectetur.

      Sed ac ullamcorper libero. Vivamus non ex at nibh sollicitudin fermentum in ac quam. Morbi aliquam, tellus ut sollicitudin pharetra, nisi mauris luctus tortor, non mollis diam nulla id lorem. Aenean quis nunc quam. Sed tempus metus vel neque lobortis, vitae consectetur purus imperdiet. Nulla iaculis molestie ligula ac efficitur. Vivamus quis accumsan risus, vitae vehicula velit. Quisque iaculis, est eu fermentum ullamcorper, tortor dolor semper lacus, ut lacinia leo lectus et urna. Donec in purus tempus, tristique orci in, mattis neque. Vivamus at consequat lorem, ultricies semper nisl. Sed sed gravida nulla. Vestibulum eget erat non dui tempor tincidunt sit amet vitae libero. Duis semper, metus sed pellentesque convallis, neque lectus porttitor tortor, accumsan viverra sem ante vitae ligula. Aliquam mattis varius mi et aliquam. Curabitur quis leo eu ex tempus dapibus ut vitae enim. Pellentesque vitae risus risus.

      Aliquam erat volutpat. Donec at neque quis eros molestie consequat. In volutpat ullamcorper metus nec dignissim. Nullam maximus lorem id mauris eleifend rutrum. Donec vulputate consectetur pellentesque. Aliquam erat volutpat. Pellentesque rutrum consequat nulla, a consectetur dolor iaculis a. In neque orci, dignissim ut magna eget, convallis sodales lectus. Maecenas eu auctor dui. Proin eget enim vel leo ullamcorper elementum eu sed ante. Phasellus in massa tortor.

      Maecenas vestibulum risus ac iaculis dignissim. Integer accumsan arcu sit amet metus interdum dignissim. Phasellus suscipit libero vel faucibus auctor. Donec non convallis libero, in tristique sem. Suspendisse ac quam lacus. Integer ligula arcu, pharetra viverra sodales at, vehicula consequat libero. Suspendisse non odio varius, euismod libero in, facilisis magna. Interdum et malesuada fames ac ante ipsum primis in faucibus.

      Aliquam bibendum at ante sed vehicula. Vestibulum sollicitudin nisi vel ante porta, et feugiat orci condimentum. Nullam id nisl non felis egestas tempus. Integer tincidunt urna euismod quam lacinia, eget interdum purus maximus. Suspendisse magna elit, feugiat nec cursus in, dictum at massa. Vestibulum tempor, arcu et accumsan consequat, nisi est lacinia arcu, pharetra bibendum eros purus et ligula. Sed consectetur tortor sem, ut auctor magna ultrices vel. Nunc porttitor condimentum bibendum. Integer ac porta dolor. Vestibulum ultrices mauris eu elementum ullamcorper. Integer quis felis ac sapien lacinia tempor. Morbi imperdiet placerat hendrerit. Fusce ligula mauris, ornare sit amet elit eget, finibus ullamcorper nisl. Ut diam purus, tempus eget augue quis, tristique tincidunt tellus. Praesent iaculis risus non nisi gravida blandit.

      Nulla vitae congue nunc. Quisque vehicula mauris sed porta placerat. Fusce neque nunc, dapibus sit amet leo eget, euismod ultricies libero. Donec accumsan turpis sit amet orci tempus, ut elementum erat vehicula. Praesent lorem nibh, imperdiet at placerat et, dignissim in tellus. Fusce volutpat feugiat sem, eu porttitor ex efficitur eget. Aenean id elit sit amet orci maximus rutrum. Cras non urna elit. Nam suscipit vestibulum metus eget ultricies. Sed sit amet gravida purus. Duis vitae varius justo, ac tristique nibh. Proin viverra mauris nec erat tristique vulputate.

      Nam massa neque, placerat nec nunc mollis, sollicitudin laoreet ante. In pretium urna lectus, et suscipit nibh lobortis non. Vivamus varius orci vitae dolor efficitur, id vehicula urna luctus. Maecenas ipsum sem, luctus a ultricies eu, eleifend ut neque. Nullam vestibulum convallis erat, eu consectetur ipsum tristique ac. Duis dignissim tincidunt massa, ac gravida magna blandit sodales. Quisque a sollicitudin risus, id feugiat magna. Quisque ultricies felis non urna gravida, sed interdum eros interdum. Suspendisse lacinia, orci ut tincidunt tempus, odio diam maximus dolor, et dapibus quam lorem vel erat. Sed quis dolor id nunc eleifend feugiat. Duis suscipit nibh eget felis consequat, eget placerat leo bibendum.

      Sed eget massa aliquet, gravida mi id, facilisis ligula. Ut euismod sem ligula, gravida cursus nunc sagittis eget. Etiam et quam sapien. Nam sed tempor dolor, vulputate maximus libero. Phasellus rhoncus aliquet velit quis dictum. Nam nec sem sed est iaculis pharetra id vitae nisl. Suspendisse mi nulla, pulvinar et ipsum ac, lobortis eleifend nisi. Curabitur eget urna ac metus blandit finibus. Ut vehicula erat eu interdum condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec semper orci nibh, vel pretium felis commodo eu. Sed sed risus malesuada, posuere metus nec, dignissim odio. Aenean id pharetra libero, ac facilisis sem. Proin non egestas nunc. Integer volutpat vel leo quis tincidunt. Aenean volutpat rutrum ligula, sit amet pretium orci eleifend sed.

      Donec vel efficitur orci, non sodales elit. Vivamus vehicula ut leo nec egestas. Vestibulum metus nisi, consequat at mi non, rhoncus iaculis neque. In finibus congue massa ut iaculis. Ut faucibus leo nec massa interdum feugiat. Nam eleifend pellentesque tellus, sodales rhoncus quam porttitor sed. Aliquam et urna justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris placerat leo quis urna viverra lobortis. Nam malesuada ex sed nibh semper suscipit. Praesent sit amet velit cursus, vestibulum tellus consequat, tincidunt sapien. Curabitur et orci ac dui condimentum ullamcorper quis eget nisi.

      Duis placerat odio quam, porttitor facilisis elit vestibulum eu. Curabitur auctor, massa in maximus dignissim, tellus elit commodo enim, non faucibus mi lectus vitae erat. Aenean blandit bibendum elit, vitae sodales nulla elementum quis. Quisque euismod nulla urna. Nunc leo ligula, tristique a tortor ut, tempor pellentesque elit. Praesent tempus porttitor mi, in rutrum magna tempus in. Cras porta mauris sed tempor laoreet. Maecenas a dolor lorem. Praesent pellentesque blandit mi quis fringilla. Sed posuere risus quis est feugiat, sit amet laoreet eros imperdiet. Etiam ut ante facilisis enim fermentum tristique vel a ligula. Pellentesque iaculis consectetur risus, nec feugiat diam bibendum id. Aliquam erat volutpat. Integer ac fermentum nunc, non iaculis erat.

      Praesent vulputate ligula nec nisl efficitur, quis fermentum lacus bibendum. Aenean viverra ligula vitae odio elementum tincidunt. Morbi nunc dui, condimentum eu semper et, rutrum sed felis. Integer imperdiet ligula ligula, ut sagittis elit tincidunt ut. Proin quis est nibh. Donec volutpat odio molestie suscipit porta. Nunc eget ex a velit facilisis vulputate ac et purus. Curabitur porttitor quam felis, sed tempor est euismod eget. Aliquam mollis tortor vitae convallis pellentesque. Integer et sapien dapibus, varius turpis vel, auctor ex. Donec ut libero in turpis suscipit auctor. Pellentesque tristique pulvinar auctor. Nunc commodo elit dictum, finibus dolor non, vehicula diam.

      Nulla efficitur nulla egestas, euismod justo vel, facilisis eros. Suspendisse tristique libero eu urna pulvinar efficitur. Curabitur imperdiet eget eros et tristique. Maecenas egestas dictum erat ac vehicula. Nam sit amet congue urna, fringilla accumsan lorem. Cras eget suscipit lacus. Mauris condimentum pulvinar consequat. Duis eget auctor odio. Praesent suscipit cursus augue eget viverra. Donec tempor leo suscipit arcu placerat, at pretium turpis ornare. Quisque scelerisque justo nec dictum lobortis. Donec condimentum nunc purus, eget pellentesque lorem mollis sed. Phasellus ornare mattis lorem, et maximus ipsum dignissim vitae. Mauris pharetra, libero et tincidunt elementum, velit velit commodo tellus, non laoreet purus lacus eu lacus.

      Quisque purus turpis, vulputate sed semper eget, molestie non mauris. Maecenas ultrices quam nunc, ut posuere lorem malesuada eu. Duis sollicitudin ullamcorper sem vel eleifend. Curabitur aliquam gravida dolor, eget faucibus quam rhoncus ut. Suspendisse vitae risus ac neque rhoncus dignissim in et purus. Donec consectetur lectus eu sem mollis feugiat. Proin sed rhoncus odio. Pellentesque euismod ultricies metus, a mattis lectus scelerisque a. Duis at libero at enim malesuada molestie quis non dolor. Aliquam tincidunt magna eu quam efficitur venenatis. Phasellus gravida pulvinar sodales. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam ligula elit, ultricies non quam nec, rhoncus condimentum purus.

      Ut vel ultrices diam. Duis tempor molestie enim, in tristique neque vehicula ac. Curabitur in erat et velit auctor sodales. Donec non lorem ante. Nulla mollis condimentum sapien in imperdiet. Donec semper diam et dapibus condimentum. Aenean felis velit, hendrerit ac nisl a, sollicitudin volutpat elit. Vivamus vel nisi tellus.

      Nullam malesuada nunc id congue fermentum. Vestibulum non sem eu nunc vestibulum dapibus. Praesent in nibh ac erat fringilla efficitur. Ut quis eros eget orci lobortis posuere at eu libero. Cras pellentesque, purus eu auctor dictum, libero erat vestibulum sapien, et lacinia mi sem eget orci. Curabitur ut turpis eleifend, maximus metus ut, pretium orci. Fusce sit amet mauris fermentum, efficitur ante quis, aliquet est. Morbi tempor tempus ante, vitae dapibus risus dignissim nec. Pellentesque ac ante in quam viverra vestibulum. Etiam vel dui varius, fermentum mi eget, maximus erat. Donec sagittis at turpis in fringilla. Ut viverra ligula eu ultrices fringilla. In et ante condimentum, pulvinar magna ut, rutrum enim.

      Integer scelerisque dolor vitae ligula varius condimentum. In malesuada, dolor ut ullamcorper dignissim, augue odio imperdiet eros, sit amet consequat ex risus vestibulum libero. Maecenas id quam massa. Morbi erat odio, eleifend ut lacus at, malesuada posuere sapien. Proin orci sem, tempor id porta quis, eleifend ut nisl. Cras id elit fermentum, posuere tortor at, pulvinar nunc. Pellentesque ultricies viverra laoreet.

      Morbi eget sem quam. Nam eu dolor sit amet erat dapibus feugiat. Integer accumsan rutrum facilisis. In hac habitasse platea dictumst. Cras varius est dui, nec porta sapien volutpat et. Integer porttitor, nulla sed posuere lobortis, est tortor cursus justo, pretium semper eros dolor et metus. Duis tempus, nunc vitae facilisis suscipit, elit nisl fringilla quam, venenatis vehicula orci libero quis justo. Sed venenatis vulputate tempus. Suspendisse nec turpis a tortor fringilla fermentum.

      Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus tincidunt, lorem vel rutrum rhoncus, sapien magna pulvinar lacus, id blandit urna dui sed turpis. Donec ut tellus pulvinar, venenatis odio ac, tempor ex. Praesent posuere id turpis ut sollicitudin. Donec id ante ligula. In sed cursus massa. Vestibulum vel aliquet dolor, eget vestibulum libero. Fusce congue tellus erat, placerat aliquam nulla ornare varius. Duis pharetra massa sit amet laoreet bibendum. Aliquam erat volutpat. Aliquam tincidunt odio quis ornare varius. Vestibulum nulla dolor, rutrum non interdum sed, facilisis quis purus.

      Integer lacinia neque id nulla ultricies varius. Integer auctor purus dignissim cursus pellentesque. Vestibulum porttitor dui libero, sed pulvinar turpis venenatis ut. Ut vitae rutrum libero. Ut ac semper quam. Vivamus tristique purus lorem, at varius risus egestas sit amet. Quisque erat mauris, pretium non finibus vitae, sodales in sem. Proin quis vehicula orci. In facilisis iaculis nulla et cursus. Nunc tincidunt est a massa aliquam pharetra vitae id tellus. Suspendisse non consequat felis. Aliquam urna nulla, porta a consectetur a, ullamcorper sed ipsum. Vivamus ultricies nulla eget neque ullamcorper, sit amet euismod metus malesuada. Nam fermentum arcu vitae lacus tristique, nec scelerisque purus facilisis.

      Nulla facilisi. Cras commodo mattis tincidunt. Suspendisse vitae felis mi. Pellentesque vitae massa vestibulum, sollicitudin urna non, condimentum diam. Sed rhoncus lobortis eros, vitae accumsan mi condimentum sit amet. Vivamus at felis urna. Aenean vitae feugiat mauris, eu tempor nulla. Duis id orci scelerisque, aliquet libero non, blandit magna. Nam in risus vel quam sodales vulputate. Etiam dictum tincidunt est, vitae dapibus urna auctor nec.

      Vestibulum nec risus ut neque pretium placerat vitae non urna. Duis eleifend tempor ultricies. Proin sit amet ligula in eros ullamcorper rhoncus ut vel neque. Duis et consequat velit, eget laoreet dolor. Proin congue suscipit ante, eget convallis ipsum dignissim viverra. Cras eu iaculis dolor, quis lobortis velit. Nam interdum, orci ut sagittis tempor, libero elit pulvinar nibh, a facilisis nisi lacus mattis mi. Sed efficitur cursus gravida. Aliquam sed dui at nibh volutpat commodo. Curabitur ullamcorper purus eu velit efficitur, ut pharetra mauris sagittis. Praesent varius nunc in lobortis pulvinar.

      Aliquam mollis egestas neque, a posuere urna laoreet tincidunt. Nunc consequat orci metus, a facilisis tortor porta a. Nunc non molestie velit. Donec efficitur leo quis elit aliquet aliquet. Aenean nulla risus, suscipit id velit eget, imperdiet semper sem. Etiam iaculis risus neque, vitae sodales dui sollicitudin quis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque diam ante, aliquam nec felis tempor, ullamcorper placerat arcu. Phasellus lorem magna, dictum et vehicula eget, tempus eu neque. Proin fringilla odio non mauris egestas porttitor. Cras auctor sed nunc id imperdiet. Mauris luctus velit eu nisl lacinia, in eleifend erat tincidunt. Suspendisse mattis tristique aliquet. Donec id interdum magna. Suspendisse vehicula nisl dolor, non elementum eros feugiat auctor.

      Morbi eu elit tempus, pharetra ligula vehicula, molestie tortor. Fusce volutpat purus a mi suscipit lacinia. Nunc finibus mauris sed nisl vehicula pretium. Duis viverra rhoncus turpis, sit amet pellentesque erat. Duis id egestas sem. Curabitur non maximus dolor. Praesent a enim auctor, aliquet orci quis, ultricies nunc. Vestibulum risus nisl, fringilla id tellus eu, efficitur interdum tellus. Praesent in elit lorem. Donec vitae nibh sit amet orci consequat lobortis. Vestibulum cursus pellentesque tortor vitae mattis. Maecenas hendrerit tincidunt orci, id congue augue tincidunt sed.

      Maecenas iaculis turpis et erat iaculis varius. Vestibulum tincidunt metus et augue pretium fringilla. Vivamus suscipit vestibulum est, in porta tortor porta id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut massa nulla, suscipit id velit quis, tristique vehicula tellus. Etiam sem augue, laoreet at varius quis, sodales sit amet purus. Fusce sit amet diam vitae mauris consectetur luctus at eu augue. Donec vestibulum, ligula eu auctor varius, magna velit pulvinar ipsum, quis porttitor tortor sem quis massa. Fusce sit amet enim eu enim facilisis porta in eu leo. Nunc arcu erat, porta ut augue ut, ullamcorper sodales erat.

      Sed nulla augue, placerat sed feugiat vel, mattis vitae tortor. Duis molestie ex nulla, nec scelerisque urna fermentum quis. Pellentesque ac massa nec ante scelerisque sagittis. Mauris pharetra volutpat convallis. Vivamus at elit non odio lacinia rutrum. Etiam scelerisque orci laoreet arcu vulputate, vitae efficitur nisi congue. Quisque est nibh, porta sed sem quis, consequat pharetra purus. Proin lorem tellus, efficitur ac accumsan vel, vulputate eu magna. Nam a posuere sem. Duis lorem est, auctor quis augue id, faucibus scelerisque metus. Donec egestas neque id tortor euismod condimentum.

      Suspendisse pulvinar condimentum vestibulum. Suspendisse tristique mi et arcu fringilla, nec egestas dui rhoncus. Morbi vitae egestas risus. Duis tristique mollis tortor, maximus ornare urna dapibus sed. Integer nulla tellus, cursus eget tristique non, convallis eu lacus. Duis tincidunt lacus purus, in scelerisque nulla posuere sit amet. Maecenas sed arcu eleifend, suscipit tellus non, aliquam enim. Etiam posuere ligula at lacinia tincidunt. Maecenas sed sapien in neque pellentesque tristique.

      Maecenas vel libero in sem hendrerit accumsan vitae id ligula. Morbi libero nunc, euismod sed pellentesque a, placerat ut est. Cras nisi libero, imperdiet a odio et, gravida varius nisi. Curabitur sit amet sagittis tellus, ac congue enim. Morbi quis urna risus. Maecenas neque ipsum, consequat a nisl ac, fringilla suscipit ligula. Nullam et elit mi.

      Fusce id nibh semper, blandit sapien sed, blandit tellus. Cras et dui nisl. Mauris rhoncus urna et ex aliquet, quis congue dolor ultrices. Etiam elementum nisl sit amet ante pretium gravida. Sed posuere metus vitae diam posuere fermentum non eu diam. Nulla vestibulum pellentesque metus. Aenean lobortis massa velit, iaculis pretium libero venenatis quis. In luctus quam ligula, in lacinia est suscipit eget. Morbi lacinia tortor id nulla tempus ullamcorper. Nunc efficitur, leo blandit condimentum ultricies, tellus tellus dapibus justo, sed volutpat tortor libero non quam.

      Ut suscipit quis augue sit amet sagittis. Ut tempus ultrices urna, id dapibus lacus vestibulum nec. In hac habitasse platea dictumst. Suspendisse eget velit vel tortor volutpat pellentesque. Vivamus elementum placerat mauris, et dignissim nibh consectetur porta. Integer venenatis sapien non suscipit consectetur. Praesent et fermentum lectus. In turpis augue, malesuada vel ornare sed, euismod non erat. Aliquam commodo lorem eget arcu ultrices eleifend. Morbi in efficitur purus. Quisque scelerisque in justo sed scelerisque. Integer elementum nulla turpis, vitae molestie est pulvinar in. Quisque ac quam at orci fermentum pretium. Quisque maximus, neque vitae vehicula cursus, libero enim commodo lorem, et imperdiet dui eros quis lectus.

      Pellentesque sit amet pulvinar nulla. Curabitur sit amet sapien eget lacus fringilla feugiat. Suspendisse accumsan diam luctus, lacinia ante ac, pharetra purus. Nam facilisis sodales est, et sollicitudin ante luctus eget. Mauris ut risus consequat, ultrices ante eget, scelerisque eros. Quisque fermentum quam sit amet mauris gravida, at sollicitudin metus feugiat. Fusce pharetra dapibus diam id viverra. Quisque id molestie augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam aliquet orci vel felis fermentum feugiat. Duis vestibulum maximus efficitur. Curabitur pellentesque ultricies nunc ut venenatis. Donec magna nisl, ornare id consequat at, pellentesque eget purus.

      Cras iaculis commodo luctus. Sed quis risus tincidunt, ultricies tortor et, vehicula velit. Vivamus pharetra, turpis eget condimentum condimentum, nulla ligula hendrerit mauris, dignissim egestas nunc lorem at mi. Phasellus gravida, quam in tristique faucibus, ipsum ipsum ornare eros, nec fringilla nunc ipsum vel nisl. Nullam suscipit ante ipsum, eget cursus nisi laoreet ac. Nullam bibendum lobortis vestibulum. Pellentesque mauris lacus, eleifend in lorem ac, eleifend sagittis felis. Quisque mi leo, luctus ac leo in, egestas finibus purus. Aenean imperdiet nunc ut quam interdum, efficitur mattis lacus facilisis. Aenean ultrices justo et euismod maximus. Praesent at mi diam. Duis venenatis dolor sed lacus porttitor, sed sodales libero suscipit. Suspendisse egestas, mauris eu efficitur porttitor, massa est sollicitudin erat, et vestibulum sapien odio nec sapien.

      Vivamus id massa quis ex laoreet finibus. Sed et luctus sem. Aliquam rhoncus quam ac maximus pulvinar. Quisque scelerisque aliquam magna vel bibendum. Vestibulum lobortis pulvinar molestie. In venenatis purus ac ipsum vehicula sodales. Donec hendrerit tempus ipsum, vitae suscipit elit molestie ut. Integer dolor dolor, eleifend sed dignissim nec, dictum hendrerit elit. Integer ac maximus sapien. Quisque dolor risus, porttitor non tellus at, maximus auctor magna. Sed dictum mauris elit, id euismod purus aliquam sit amet. Morbi maximus sapien id volutpat bibendum. Fusce est risus, condimentum eu varius id, mattis vitae lectus. Donec scelerisque mattis sapien, et euismod elit tempor id. Phasellus magna lacus, egestas id fermentum quis, tincidunt sed mi. Cras tincidunt urna ipsum, ac blandit nibh iaculis et.

      Aenean commodo, erat at sagittis ullamcorper, orci leo porta nulla, sit amet euismod ex diam ut turpis. Vivamus id dui quam. Proin ut quam a tellus mollis accumsan at id lorem. Suspendisse facilisis ante eu felis porta malesuada. Praesent nec gravida dui. Phasellus a sollicitudin nisi, ac gravida augue. In hac habitasse platea dictumst. Suspendisse tincidunt nisi tortor, id semper augue laoreet ut. Donec elementum sapien nisi, eu placerat neque scelerisque sit amet. Donec rhoncus condimentum posuere. Suspendisse a malesuada urna. Sed faucibus, nisi ac sodales lacinia, purus augue varius lorem, vitae faucibus libero ligula vitae lacus. Etiam luctus velit in vulputate posuere.

      Pellentesque tincidunt, felis sed facilisis elementum, ante nisl vulputate enim, vitae commodo libero mauris sed erat. Duis sit amet mattis risus, quis finibus quam. Sed quam lacus, auctor at arcu at, fringilla sagittis eros. Phasellus tincidunt nec nibh eu viverra. Donec vel lectus suscipit, consequat lorem eu, vehicula lorem. Proin lorem quam, dignissim sit amet elit et, congue tincidunt felis. Morbi pretium ornare dolor, a vehicula nisl ornare nec. Cras dapibus felis finibus sem finibus cursus. Donec eget lacus scelerisque nibh vehicula finibus. Integer non pellentesque orci, eget faucibus risus. Nullam euismod, nisi id rhoncus blandit, lacus nisl dictum urna, in sodales velit quam porttitor nisl. Donec mollis turpis vitae dui eleifend rutrum. Phasellus ultricies pellentesque convallis. Proin ultrices, lorem eu volutpat porta, quam justo dignissim neque, non aliquet arcu justo vitae felis. In pellentesque tellus nibh, in mattis risus semper nec.

      Ut et augue ac ex elementum faucibus mollis sed lorem. Fusce varius id mauris eu pharetra. Nulla feugiat lorem ac est eleifend maximus. Pellentesque vitae nibh auctor, interdum ante vel, laoreet enim. In tincidunt elit sed libero dictum, non porta nisl efficitur. Suspendisse aliquet hendrerit ligula, at luctus felis commodo sit amet. Pellentesque accumsan faucibus magna, tristique viverra ante accumsan ac. Nulla eu consectetur enim.

      Nunc venenatis arcu a lacus iaculis, sit amet convallis augue gravida. Etiam lacinia elit quis turpis luctus, commodo dignissim felis sagittis. Donec et sodales tortor. Vestibulum fermentum ligula non lectus congue faucibus. Cras imperdiet euismod magna, at porttitor augue rhoncus in. Duis facilisis ligula sollicitudin, auctor mi eu, egestas velit. Vivamus efficitur commodo metus non facilisis. Nulla facilisi. Proin pretium condimentum tellus condimentum tristique. Aenean semper nibh dui, sit amet fermentum magna varius eu. Maecenas facilisis justo ut mauris semper, a aliquam neque facilisis. Curabitur nec augue at metus consequat facilisis. Phasellus vitae erat consectetur, aliquam mi eget, dignissim diam.

      Morbi volutpat nisl quis consectetur ullamcorper. Proin facilisis, nisl in semper porta, orci urna elementum neque, a suscipit lorem leo in sem. Integer elementum eros laoreet metus blandit, et luctus nulla mattis. Suspendisse potenti. Nulla nec egestas tortor. Aliquam sit amet vulputate mi. Praesent non convallis ante. Mauris auctor tellus nibh, nec ornare est semper eu. Pellentesque ac velit tempus, tempus velit volutpat, tempor diam. Vestibulum nec pulvinar leo, non pellentesque quam. Nulla aliquam nisi nec vehicula rutrum. Donec euismod facilisis leo vitae pellentesque. Etiam sit amet vehicula sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
      <button @click="showPopup">OpenPopup</button>
      Praesent ac arcu ut augue feugiat porta. Fusce quis dapibus risus. Vivamus vitae felis et libero faucibus consectetur non in leo. Integer molestie fermentum nibh, et vehicula nibh malesuada sed. Nullam at enim convallis, ultrices tellus vitae, rhoncus lorem. Donec vel aliquam eros. Duis sit amet est metus. Duis euismod enim et aliquam tincidunt.

      Cras imperdiet ipsum a molestie consectetur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum id scelerisque velit. Sed quis venenatis quam. Duis sed diam volutpat, vestibulum sem eu, viverra libero. Nulla a efficitur odio. Cras sed euismod justo. Praesent lacinia gravida augue. Integer viverra augue velit, vitae lacinia leo hendrerit eget. Nulla eleifend quam vel maximus imperdiet. Suspendisse rutrum ante elementum fermentum dictum.

      Curabitur ut elit neque. Etiam tincidunt sollicitudin mauris, vel ultrices est tempor ac. Nam sodales arcu a sapien scelerisque, eget eleifend justo maximus. Nunc maximus mauris turpis, sed vehicula ligula interdum vitae. Nullam ac felis sed turpis dignissim volutpat. Morbi volutpat eu diam id iaculis. Duis suscipit tristique ligula, ac faucibus nunc suscipit id. Pellentesque feugiat a nibh a cursus. Suspendisse odio leo, vulputate eget lacus sit amet, malesuada elementum erat.

      Fusce vel vestibulum orci. Pellentesque tincidunt nisi at lacus blandit faucibus. Mauris luctus orci id sem iaculis pulvinar. Duis eget turpis a metus tincidunt blandit. Fusce dapibus velit et mi dignissim scelerisque. Curabitur vitae diam volutpat, venenatis augue sit amet, mollis augue. Pellentesque suscipit viverra sapien, eu dapibus ex rutrum eu. Donec urna nisi, ultrices non est in, gravida scelerisque velit. Maecenas eu aliquet purus. Nullam auctor augue nisl, porttitor ultrices mi sollicitudin eget. Donec congue elit vel elementum luctus. Ut posuere urna non nulla ornare ultricies. Duis egestas quis ipsum ac commodo.

      Etiam cursus dignissim diam et facilisis. Etiam sagittis finibus felis id tincidunt. Sed mi ligula, elementum quis urna quis, maximus tincidunt purus. Aliquam efficitur sem id varius auctor. Nam vitae accumsan sapien. Phasellus pellentesque egestas convallis. Mauris tincidunt dictum consequat. In scelerisque volutpat velit vitae malesuada. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed auctor justo eget elit hendrerit vestibulum. Donec luctus sem et nulla eleifend posuere.

      Proin neque sem, imperdiet non metus ut, rhoncus rhoncus eros. Vestibulum vel libero ac ex ultricies aliquam. Quisque euismod leo et purus venenatis ornare. Sed ornare, erat sed scelerisque vestibulum, libero eros molestie nisl, vitae fermentum sem ex in eros. Phasellus turpis dui, rutrum ac vestibulum sed, hendrerit et ante. Donec aliquet, magna nec mollis interdum, massa ex semper dolor, eget varius augue nisi vel quam. Mauris nec ante eu ipsum scelerisque porta non nec metus.

      Proin sed vehicula lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In mattis, tortor in convallis pellentesque, dui justo ultricies velit, ac suscipit sem odio tempor neque. Ut non pulvinar magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur non sapien iaculis, ornare metus a, bibendum nisl. Aenean cursus dictum odio, eu fermentum sapien iaculis vel. Proin maximus ornare bibendum. Nam quis lacus sed neque volutpat vestibulum a at nulla. Nullam enim leo, tempus non urna in, finibus mollis arcu. Praesent venenatis ex dui, vitae fermentum libero dignissim eget. Aliquam eget mauris et ex bibendum luctus. Mauris rutrum, lacus sed varius convallis, libero nulla gravida mi, sit amet venenatis eros odio id diam. Suspendisse sit amet quam id risus tincidunt congue.

      Nullam at aliquet sapien. Vestibulum in enim eget elit faucibus ultrices. Quisque luctus porttitor mollis. Fusce vitae semper erat. Ut vitae cursus odio, in porttitor enim. Donec pulvinar ultrices enim, non fringilla est venenatis vel. In viverra tempor mi. Fusce vel aliquam ante, facilisis lobortis orci.

      Donec ac risus hendrerit, efficitur libero a, tristique libero. Suspendisse a dapibus arcu. Curabitur auctor ex nec sem blandit, sit amet tincidunt nisi suscipit. Cras nec nunc sit amet dui commodo blandit. Pellentesque ut libero posuere libero posuere tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec blandit tortor vitae scelerisque consequat.

      Nam fermentum ultrices mi, et tempus diam aliquet a. Nullam in leo dapibus, faucibus tortor eget, laoreet ante. Vivamus vel maximus felis. Duis congue dolor est, vel suscipit justo feugiat nec. Sed blandit libero in lorem posuere dictum. Vestibulum blandit risus et consequat tristique. Nulla a quam dignissim, molestie nisl in, facilisis urna. Ut sed lorem vitae nulla rutrum bibendum. Proin efficitur lacinia elit. Phasellus viverra justo sit amet diam dapibus, ac dapibus risus blandit. Quisque et nisl tortor. Nam eget purus mattis, dictum lorem id, euismod purus. Phasellus fringilla imperdiet mauris, eget efficitur tellus ultrices a. Aliquam erat volutpat. Ut laoreet est vel finibus pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

      Aliquam odio libero, sollicitudin in molestie vitae, fermentum et metus. Cras efficitur malesuada ex, vel accumsan mi gravida quis. Donec cursus ex in maximus viverra. Nullam commodo semper nisi, nec porta orci tempor sed. Phasellus congue leo efficitur accumsan suscipit. Proin auctor vestibulum accumsan. Proin nulla augue, tincidunt ut tempor vel, tempor et turpis. Nulla lectus odio, sollicitudin in euismod a, condimentum ut massa. Integer ultricies ante pellentesque, tincidunt mi eget, tincidunt mi. Pellentesque pulvinar tempor orci, a condimentum eros rutrum at. Nulla efficitur dictum diam sed dignissim. Duis ut ipsum faucibus, mollis mauris in, semper velit. Morbi commodo dignissim purus, sit amet hendrerit lacus maximus non. Maecenas placerat neque in dapibus porta. Cras dictum ultricies libero. Morbi eu pretium arcu.


    </div>
  </div>
</template>

<script setup lang="ts">
import {usePopupStore} from "~/composables/popupStore/usePopupStore";
import {PopupName} from "~/composables/popupStore/types";

const popupStore = usePopupStore()
function showPopup() {
popupStore.showPopup(PopupName.Test)
  console.log(popupStore.getActivePopup.value)
}
</script>

<style scoped lang="scss">

</style>